BEGIN
    FOR rec IN (
        SELECT c.CUSTOMERID
        FROM CUSTOMERS c
        WHERE FLOOR(MONTHS_BETWEEN(SYSDATE, c.DATEOFBIRTH)/12) >= 60
    ) LOOP
        UPDATE LOANS
        SET INTERESTRATE = INTERESTRATE - 1
        WHERE CUSTOMERID = rec.CUSTOMERID;
    END LOOP;

    COMMIT;
END;
/