SELECT c.CUSTOMERID,
       c.CUSTOMERNAME,
       FLOOR(MONTHS_BETWEEN(SYSDATE, c.DATEOFBIRTH)/12) AS AGE,
       l.INTERESTRATE
FROM CUSTOMERS c
JOIN LOANS l
ON c.CUSTOMERID = l.CUSTOMERID
WHERE FLOOR(MONTHS_BETWEEN(SYSDATE, c.DATEOFBIRTH)/12) >= 60;